- name: basename {{ java_download_url }}
  command: basename {{ java_download_url }}
  register: java_tarball

- name: download {{ java_download_url }}
  get_url: url={{ java_download_url }} dest=/tmp/{{ java_tarball.stdout }}

- name: mkdir /opt/java{{ java }}
  file: path=/opt/java{{ java }} state=directory mode=0755

- name: unarchive {{ java_tarball.stdout }}
  unarchive:
    src: /tmp/{{ java_tarball.stdout }}
    dest: /opt/java{{ java }}
    copy: no
    extra_opts: ['--strip-components=1']

- name: chown /opt/java{{ java }}
  file: path=/opt/java{{ java }} owner=root group=root recurse=yes
