- name: mkdir {{ hadoop_yarn_log_dir }}
  file: path={{ hadoop_yarn_log_dir }} owner=yarn group=hadoop mode=0755 state=directory

- name: mkdir yarn container log dir
  file: path={{ item }}/yarnLogs owner=yarn group=hadoop mode=0755 state=directory
  with_items: "{{ hadoop_workspace }}"

- name: mkdir nodemgr local dir
  file: path={{ item }}/nodemgr owner=yarn group=hadoop mode=0755 state=directory
  with_items: "{{ hadoop_workspace }}"
