- name: '{{ nagios_install_dir }}/bin/nagios -v {{ nagios_install_dir }}/etc/nagios.cfg'
  shell: '{{ nagios_install_dir }}/bin/nagios -v {{ nagios_install_dir }}/etc/nagios.cfg'

- name: generate /etc/profile.d/nagios.sh
  template: src=nagios.sh.j2 dest=/etc/profile.d/nagios.sh

- name: generate nagios conf files
  template: src={{ item }}.j2 dest={{ nagios_install_dir }}/etc/{{ item }}
  with_items:
    - cgi.cfg
    - nagios.cfg
    - resource.cfg

- name: generate nagios object conf files
  template: src={{ item }}.j2 dest={{ nagios_install_dir }}/etc/objects/{{ item }}
  with_items:
    - templates.cfg
    - contacts.cfg
    - timeperiods.cfg
    - commands.cfg
    - hosts.cfg
    - services.cfg

- name: generate nagios plugins
  template: src={{ item }}.j2 dest={{ nagios_install_dir }}/libexec/{{ item }} mode=0755
  with_items:
    - send_mail.py
    - send_sms.py
    - phone_call.py
    - check_for_stuck_gmonds.sh
    - check_ganglia_metric.sh
    - check_heartbeat.sh
    - check_host_regex.sh
    - check_metric_regex.sh
    - check_multiple_metrics.sh
    - check_multiple_metrics_warn.sh
    - check_value_same_everywhere.sh

- name: create htpasswd for {{ nagios_admin_username }}
  htpasswd:
    path: '{{ nagios_install_dir }}/etc/htpasswd.users'
    name: '{{ nagios_admin_username }}'
    password: '{{ nagios_admin_passwd }}'

- name: create htpasswd for {{ nagios_readonly_username }}
  htpasswd:
    path: '{{ nagios_install_dir }}/etc/htpasswd.users'
    name: '{{ nagios_readonly_username }}'
    password: '{{ nagios_readonly_passwd }}'

