- name: basename {{ nagios_plugins_download_url }}
  command: basename {{ nagios_plugins_download_url }}
  register: nagios_plugins_tarball

- name: download {{ nagios_plugins_download_url }}
  get_url: url={{ nagios_plugins_download_url }} dest=/tmp/{{ nagios_plugins_tarball.stdout }}

- name: create temporary build directory
  tempfile:
    state: directory
    suffix: build
  register: tempdir

- name: unarchive /tmp/{{ nagios_plugins_tarball.stdout }}
  unarchive:
    src: /tmp/{{ nagios_plugins_tarball.stdout }}
    dest: '{{ tempdir.path }}'
    copy: no
    extra_opts: ['--strip-components=1']

- name: configure nagios-plugins
  shell: './configure --with-nagios-user=nagios --with-nagios-group=nagios --prefix={{ nagios_install_dir }}'
  args:
    chdir: '{{ tempdir.path }}'

- name: build nagios-plugins
  shell: 'make all'
  args:
    chdir: '{{ tempdir.path }}'

- name: install nagios-plugins
  shell: 'make install'
  args:
    chdir: '{{ tempdir.path }}'
