- name: chown {{ nagios_install_dir }}
  file: path={{ nagios_install_dir }} owner=nagios group=nagios recurse=yes state=directory

- name: enable & restart nagios
  service: name=nagios state=restarted enabled=yes

- name: enable & restart httpd
  service: name=httpd state=restarted enabled=yes
