- name: generate uuid
  command: uuidgen
  register: uuid

- name: generate all config files
  template: src={{ item }}.j2  dest=/etc/presto/{{ item }} owner=root group=root
  with_items:
    - env.sh
    - jvm.config
    - config.properties
    - log.properties
    - node.properties

- name: generate catalog config files
  template: src={{ item }}.j2  dest=/etc/presto/catalog/{{ item }} owner=root group=root
  with_items:
    - hive.properties

