- name: download presto repo
  get_url: url={{ presto_repo_url }} dest=/etc/yum.repo.d/

- name: yum install presto-server
  yum: name=presto-server state=present

- name: mkdir /etc/presto/catalog
  file: path=/etc/presto/catalog state=directory owner=root group=root mode=0755

- name: mkdir {{ presto_data_dir }}
  file: path={{ presto_data_dir }} state=directory owner=presto group=presto mode=0755
