- name: mkdir /tmp/app_keytab
  local_action:
    module: file
    path: /tmp/app_keytab
    state: directory
    owner: root
    group: root
    mode: 0700

- name: generate yarn.keytab (yarn)
  local_action: command sh create_app_keytab.sh yarn {{ inventory_hostname }} /tmp/app_keytab/{{ inventory_hostname }}_yarn.keytab

- name: generate yarn.keytab (HTTP)
  local_action: command sh create_app_keytab.sh HTTP {{ inventory_hostname }} /tmp/app_keytab/{{ inventory_hostname }}_yarn.keytab

- name: mkdir /etc/security/keytab
  file: path=/etc/security/keytab state=directory owner=root group=root mode=0755

- name: copy keytab to remote host
  copy: src=/tmp/app_keytab/{{ inventory_hostname }}_yarn.keytab dest=/etc/security/keytab/yarn.keytab owner=yarn group=hadoop mode=0400
