- name: mkdir {{ hadoop_hdfs_log_dir }}
  file: path={{ hadoop_hdfs_log_dir }} owner=hdfs group=hadoop mode=0755 state=directory

- name: mkdir datanode dfs data dir
  file: path={{ item }}/dfs/data owner=hdfs group=hadoop mode=0700 state=directory
  with_items: "{{ hadoop_workspace }}"

- name: mkdir /var/lib/hadoop-hdfs
  file: path=/var/lib/hadoop-hdfs owner=hdfs group=hadoop mode=0755 state=directory
