---
- hosts: historyserver
  vars_files:
    - ../config.yml
  user: root
  tasks:
    - name: stop historyserver
      command: mr-jobhistory-daemon.sh stop historyserver
      become: true
      become_user: mapred
      become_method: su
      become_flags: '-s /bin/sh'

    - name: sleep 2s
      command: sleep 2

    - name: start historyserver
      command: mr-jobhistory-daemon.sh start historyserver
      become: true
      become_user: mapred
      become_method: su
      become_flags: '-s /bin/sh'

    - name: sleep 2s
      command: sleep 2
