---
- hosts: proxyserver
  vars_files:
    - ../config.yml
  user: root
  tasks:
    - name: stop proxyserver
      command: yarn-daemon.sh stop proxyserver
      become: true
      become_user: yarn
      become_method: su
      become_flags: '-s /bin/sh'

    - name: sleep 2s
      command: sleep 2

    - name: start proxyserver
      command: yarn-daemon.sh start proxyserver
      become: true
      become_user: yarn
      become_method: su
      become_flags: '-s /bin/sh'

    - name: sleep 2s
      command: sleep 2
