---
- hosts: spark_historyserver
  vars_files:
    - ../config.yml
  user: root
  tasks:
    - name: stop spark historyserver
      command: stop-history-server.sh
      become: true
      become_user: spark
      become_method: su
      become_flags: '-s /bin/sh'

    - name: sleep 2s
      command: sleep 2

    - name: start spark historyserver
      command: start-history-server.sh
      become: true
      become_user: spark
      become_method: su
      become_flags: '-s /bin/sh'
