---
- hosts: resourcemanager
  vars_files:
    - ../config.yml
  user: root
  tasks:
    - name: stop resourcemanager
      command: yarn-daemon.sh stop resourcemanager
      become: true
      become_user: yarn
      become_method: su
      become_flags: '-s /bin/sh'

    - name: sleep 2s
      command: sleep 2

    - name: start resourcemanager
      command: yarn-daemon.sh start resourcemanager
      become: true
      become_user: yarn
      become_method: su
      become_flags: '-s /bin/sh'

    - name: sleep 2s
      command: sleep 2
