---
- hosts: master
  vars_files:
    - ../config.yml
  user: root
  tasks:
    - name: stop hbase master
      command: hbase-daemon.sh stop master
      become: true
      become_user: hbase
      become_method: su
      become_flags: '-s /bin/sh'

    - name: sleep 2s
      command: sleep 2

    - name: start hbase master
      command: hbase-daemon.sh start master
      become: true
      become_user: hbase
      become_method: su
      become_flags: '-s /bin/sh'

    - name: sleep 5m
      command: sleep 300
