---
- hosts: nodemanager
  vars_files:
    - ../config.yml
  user: root
  tasks:
    - name: start nodemanager
      command: yarn-daemon.sh start nodemanager
      become: true
      become_user: yarn
      become_method: su
      become_flags: '-s /bin/sh'
