---
- hosts: journalnode
  vars_files:
    - ../config.yml
  user: root
  tasks:
    - name: start journalnode
      command: hadoop-daemon.sh start journalnode
      become: true
      become_user: hdfs
      become_method: su
      become_flags: '-s /bin/sh'
