---
- hosts: master
  vars_files:
    - ../config.yml
  user: root
  tasks:
    - name: stop hbase master
      command: hbase-daemon.sh stop master
      become: true
      become_user: hbase
      become_method: su
      become_flags: '-s /bin/sh'
