---
- hosts: namenode
  vars_files:
    - ../config.yml
  user: root
  tasks:
    - name: stop namenode
      command: hadoop-daemon.sh stop namenode
      become: true
      become_user: hdfs
      become_method: su
      become_flags: '-s /bin/sh'
