---
- hosts: kafka
  vars_files:
    - ../config.yml
  user: root
  tasks:
    - name: stop kafka
      command: kafka-server-stop.sh
      become: true
      become_user: kafka
      become_method: su
      become_flags: '-s /bin/sh'
