---
- hosts: hive
  vars_files:
    - ../config.yml
  user: root
  tasks:
    - name: stop hiveserver2
      shell: "kill -9 `ps ax --cols 2000 | grep java | grep HiveServer2 | grep -v 'ps ax' | awk '{print $1;}'`"
      become: true
      become_user: hive
      become_method: su
      become_flags: '-s /bin/sh'
