---
- hosts: datanode
  vars_files:
    - ../config.yml
  user: root
  tasks:
    - name: stop datanode
      command: hadoop-daemon.sh stop datanode
      become: true
      become_user: hdfs
      become_method: su
      become_flags: '-s /bin/sh'
