- name: mkdir /tmp/app_keytab
  local_action:
    module: file
    path: /tmp/app_keytab
    state: directory
    owner: root
    group: root
    mode: 0700

- name: generate hive.keytab (hive)
  local_action: command sh create_app_keytab.sh hive {{ inventory_hostname }} /tmp/app_keytab/{{ inventory_hostname }}_hive.keytab

- name: generate hive.keytab (HTTP)
  local_action: command sh create_app_keytab.sh HTTP {{ inventory_hostname }} /tmp/app_keytab/{{ inventory_hostname }}_hive.keytab

- name: mkdir /etc/security/keytab
  file: path=/etc/security/keytab state=directory owner=root group=root mode=0755

- name: copy keytab to remote host
  copy: src=/tmp/app_keytab/{{ inventory_hostname }}_hive.keytab dest=/etc/security/keytab/hive.keytab owner=hive group=hadoop mode=0400
